apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgres.appName | default "adminer-postgres" }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.password | default (randAlphaNum 64) }}
  replication-password: {{ .Values.replicationPassword | default (randAlphaNum 64) }}
type: Opaque
