# Adminer Config

global:
  adminer:
    # App Name
    appName: adminer
    # Port
    port: 8080
    # Service Name (for: <pod-name>.<serviceName>.default.svc.cluster.local)
    serviceName: adminer
    # Label Name (for app.kubernetes.io/name), make sure this label doesn't collide with other resources in your namespace
    labelName: adminer

# Replicas (scale up or down)
replicas: 1

# Misc

# Resources
resources:
  minimumCPU:
  maximumCPU:
  minimumRAM:
  maximumRAM:

# Service extra spec (override default config, e.g. use LoadBalancer instead of ClusterIP)
service:
  extraSpec:
