apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.adminer.appName }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
data:
  default-server: {{ .Values.global.postgres.appName }}-0.{{ .Values.global.postgres.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
