apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.adminer.appName }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
data:
  default-server: {{ .Values.postgres.appName }}-0.{{ .Values.postgres.serviceName }}.default.svc.cluster.local
