apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.appName | default "adminer-postgres" }}
  labels:
    {{- include "adminer-postgres.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.postgres.password | default (randAlphaNum 64) }}
  replication-password: {{ .Values.postgres.replicationPassword | default (randAlphaNum 64) }}
type: Opaque
