apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName | default "adminer-postgres" }}
spec:
  selector:
    {{- include "adminer-postgres.labels" . | nindent 4 }}
  clusterIP: None
  ports:
    - name: db-port
      port: {{ .Values.postgres.port | default 5432 }}
