name: CI Job
run-name: ${{ github.actor }} has triggered the CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 #v6
      - name: Helm tool installer
        uses: Azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 #v5.0.1
        with:
          version: '4.2.0'
      - run: helm lint charts/
  test:
    needs: [lint]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Install Helm
        uses: Azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 #v5.0.1
        with:
          version: '4.2.0'
      - name: Install helm-unittest
        run: helm plugin install --verify=false oci://ghcr.io/helm-unittest/helm-unittest/unittest@sha256:0d833da8404eac789412ba37f71955f842bfaa358e20ed89bc4366fe1f1acad2
      - name: Install dependencies
        run: cd charts/ && helm dependency build && cd ..
      - name: Run tests
        run: bash test.sh

  changes:
    needs: [test]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      current_version: ${{ steps.check.outputs.current }}
      chart_name: ${{ steps.check.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          fetch-depth: 3

      - name: Check if chart version changed
        id: check
        run: |
          prev=$(git show HEAD^:charts/Chart.yaml | yq '.version')
          curr=$(yq '.version' charts/Chart.yaml)
          if [ "$prev" != "$curr" ]; then
            echo "version_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
          fi
          echo "current=$curr" >> "$GITHUB_OUTPUT"

          name=$(yq '.name' charts/Chart.yaml)
          echo "name=$name" >> "$GITHUB_OUTPUT"

  release-repo:
    needs: [test, changes]
    if: github.ref == 'refs/heads/main' && needs.changes.outputs.version_changed == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "hi@dariush.dev"
      - name: Run Helm Releaser
        uses: helm/chart-releaser-action@3e001cb8c68933439c7e721650f20a07a1a5c61e
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-oci:
    needs: [test, changes]
    if: github.ref == 'refs/heads/main' && needs.changes.outputs.version_changed == 'true'
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: Azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 #v5.0.1
        with:
          version: '4.2.0'
      - name: Install dependencies
        run: cd charts/ && helm dependency build && cd ..
      - name: Package chart
        run: helm package charts/ --version $VERSION
        env:
          VERSION: "${{ needs.changes.outputs.current_version }}"
      - name: Login to GHCR
        run: echo "$GH_TOKEN" | helm registry login -u "$GITHUB_ACTOR" --password-stdin ghcr.io
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN  }}"
      - name: Convert owner to lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - name: Push image to GHCR
        run: helm push $NAME-$VERSION.tgz oci://ghcr.io/${{ env.OWNER_LC }}
        env:
          NAME: "${{ needs.changes.outputs.chart_name }}"
          VERSION: "${{ needs.changes.outputs.current_version }}"
